---
- hosts: myhosts
  connection: local
  name: Get Virtual Media information
  gather_facts: False

  vars:
    datatype: VirtualMedia

  tasks:

  - name: Define output file
    include_tasks: create_output_file.yml

  - name: Get Virtual Media information from Manager
    redfish_info:
      category: Manager
      command: GetVirtualMedia
      baseuri: "{{ baseuri }}"
      username: "{{ username }}"
      password: "{{ password }}"
    register: result

  - name: Copy results to output file
    copy:
      content: "{{ result.redfish_facts.virtual_media.entries | to_nice_json }}"
      dest: "{{ template }}.json"
    when: result.redfish_facts.virtual_media.ret

  - name: Set var virtualMedia
    set_fact:
      virtualMedia: "{{ result.redfish_facts.virtual_media.entries[0][1] }}"
    when: result.redfish_facts.virtual_media.ret

  - block:
    - name: Get Virtual Media information from Systems
      redfish_info:
        category: Systems
        command: GetVirtualMedia
        baseuri: "{{ baseuri }}"
        username: "{{ username }}"
        password: "{{ password }}"
      register: result2
    
    - name: Copy results to output file
      copy:
        content: "{{ result2.redfish_facts.virtual_media.entries | to_nice_json }}"
        dest: "{{ template }}.json"

    - name: Set var virtualMedia
      set_fact:
        virtualMedia: "{{ result2.redfish_facts.virtual_media.entries[0][1] }}"
    when: not result.redfish_facts.virtual_media.ret

